/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miPaquete;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class vistaRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public vistaRegistrar() {
        initComponents();
        cargarElementosAComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        correoClienteTextField = new javax.swing.JTextField();
        nombreClienteTextField = new javax.swing.JTextField();
        direccionClienteTextField = new javax.swing.JTextField();
        ultimaVisitaTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        modeloComboBox = new javax.swing.JComboBox<>();
        colorComboBox = new javax.swing.JComboBox<>();
        registrarjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        marcaComboBox = new javax.swing.JComboBox<>();
        placasTextField = new javax.swing.JTextField();
        kilometrajeTextField = new javax.swing.JTextField();
        numeroSerieTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submarcaComboBox = new javax.swing.JComboBox<>();
        numeroTelefonicoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nombreServiciojComboBox = new javax.swing.JComboBox<>();
        costojTextField = new javax.swing.JTextField();
        mecanicoAsignadojComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        idDeServiciojTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        observacionesMecanicojText = new javax.swing.JTextField();
        observacionesClientejTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButtonAtras1 = new javax.swing.JButton();
        fechaEntregajTextField = new javax.swing.JTextField();
        fechaLLegadajTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 450));
        setResizable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1819, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 339, -1, -1));

        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 342, -1, -1));
        jPanel1.add(correoClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 210, -1));
        jPanel1.add(nombreClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 298, 180, -1));
        jPanel1.add(direccionClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 339, 180, -1));
        jPanel1.add(ultimaVisitaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 386, 90, -1));

        jLabel16.setText("Color");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 95, -1, -1));

        jLabel10.setText("Kilometraje");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 161, -1, -1));

        jLabel11.setText("Numero de Serie");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 212, -1, -1));

        jLabel12.setText("Ultima Visita");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 386, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Registro Automovil");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Registro Dueño");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jPanel1.add(modeloComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 38, 144, -1));

        jPanel1.add(colorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 92, 113, -1));

        registrarjButton.setText("Registrar");
        registrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registrarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 83, 36));

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 41, -1, -1));

        jLabel4.setText("Fecha de llegada");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 480, -1, -1));

        jLabel17.setText("Fecha de entrega");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 519, -1, -1));

        marcaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seleccionarSubmarca(evt);
            }
        });
        jPanel1.add(marcaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 38, 113, -1));
        jPanel1.add(placasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 149, 144, -1));
        jPanel1.add(kilometrajeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 158, 110, -1));
        jPanel1.add(numeroSerieTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 250, -1));

        jLabel2.setText("Marca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 41, -1, -1));

        jLabel3.setText("Submarca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 95, -1, -1));

        jPanel1.add(submarcaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 92, 142, -1));
        jPanel1.add(numeroTelefonicoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 120, -1));

        jLabel5.setText("Placas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 152, -1, -1));

        jLabel6.setText("Nombre del Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 298, -1, -1));

        jLabel7.setText("Numero Telefonico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 301, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Registro Servicio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jLabel18.setText("Nombre del Servicio");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 480, -1, -1));

        jLabel19.setText("Costo");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 525, -1, -1));

        jLabel20.setText("Mecanico Asignado");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 563, -1, -1));

        jPanel1.add(nombreServiciojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 90, -1));
        jPanel1.add(costojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 90, -1));

        jPanel1.add(mecanicoAsignadojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 90, -1));

        jLabel21.setText("Id Servicio");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 557, -1, -1));
        jPanel1.add(idDeServiciojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 554, 90, -1));

        jLabel22.setText("Observaciones del cliente:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 599, -1, -1));

        jLabel23.setText("Observaciones del mecanico:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 599, -1, -1));
        jPanel1.add(observacionesMecanicojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 634, 231, 60));
        jPanel1.add(observacionesClientejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 634, 231, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miPaquete/imagenes/audi-automobile-car-lights-1149831.jpg"))); // NOI18N
        jLabel24.setToolTipText("");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 190, 150));

        jButtonAtras1.setText("Atrás");
        jButtonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtras1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 712, 83, 36));
        jPanel1.add(fechaEntregajTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 90, -1));
        jPanel1.add(fechaLLegadajTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 90, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarjButtonActionPerformed
        String placas = placasTextField.getText();
        String submarca = (String) submarcaComboBox.getSelectedItem();
        String nombreCliente = nombreClienteTextField.getText();
        String idDeServicio = idDeServiciojTextField.getText();
        String direccion = direccionClienteTextField.getText();
        String correo = correoClienteTextField.getText();
        String ultimaVisita = ultimaVisitaTextField.getText();
        String nombreDelServicio = (String) nombreServiciojComboBox.getSelectedItem();
        String observacionesCliente = observacionesClientejTextField.getText();

        String mecanicoAsignado = (String) mecanicoAsignadojComboBox.getSelectedItem();;
        String fechaLLegada = fechaLLegadajTextField.getText();
        String fechaEntrega = fechaEntregajTextField.getText();
        String modelo = (String) modeloComboBox.getSelectedItem();
        String marca = (String) marcaComboBox.getSelectedItem();
        String color = (String) colorComboBox.getSelectedItem();

        double costo = 0;
        String telefono = numeroTelefonicoTextField.getText();
        String kilometraje = kilometrajeTextField.getText();
        String numeroDeSerie = numeroSerieTextField.getText();
        String observacionesMecanico = observacionesMecanicojText.getText();

        try {

            costo = Double.parseDouble(costojTextField.getText());

        } catch (Exception e) {
            System.out.println(e);
            System.out.println("Problema al convertir de String a int o double");
        }

        if (!idDeServiciojTextField.getText().equals("") && !placasTextField.getText().equals("")
                && !direccionClienteTextField.getText().equals("") && !kilometrajeTextField.getText().equals("")
                && !nombreClienteTextField.getText().equals("") && !numeroSerieTextField.getText().equals("")
                && !numeroTelefonicoTextField.getText().equals("") && !correoClienteTextField.getText().equals("")
                && !ultimaVisitaTextField.getText().equals("") && !costojTextField.getText().equals("")
                && !fechaEntregajTextField.getText().equals("") && !fechaLLegadajTextField.getText().equals("")) {
            try {

                File file = new File("miArchivo2.txt");
                BufferedReader reader = null;
                boolean found = false;

                try {
                    // FileReader reads text files in the default encoding.
                    FileReader fl = new FileReader(file);
                    String ID = "";
                    // Always wrap FileReader in BufferedReader.
                    reader = new BufferedReader(fl);
                    String text;

                    while ((text = reader.readLine()) != null) {

                        StringTokenizer st1 = new StringTokenizer(text, "%");

                        while (st1.hasMoreElements() && !found) {
                            ID = (String) st1.nextElement();

                            if (ID.equals(idDeServicio + "RM")) {
                                found = true;

                            }
                        }
                    }

                    if (found) {
                        System.out.println("Numero Encontrado Dentro De (Repetido)");
                        mostrarMensajeEmergente("Error", "Registro repetido");

                    } else {
                        System.out.println("Numero no Encontrado DENTRO (Unico)");

                        try {
                            Controlador.registrarServicio(idDeServicio, nombreDelServicio, costo, mecanicoAsignado, observacionesCliente, fechaLLegada, fechaEntrega, modelo, marca, color, submarca, placas, kilometraje, numeroDeSerie, nombreCliente, direccion, telefono, correo, ultimaVisita, observacionesMecanico);
                            Scanner scan = new Scanner(file);
                            String filecontent = (idDeServicio + "RM" + "%" + nombreDelServicio + "%" + costo + "%" + mecanicoAsignado + "%" + fechaLLegada + "%" + fechaEntrega + "%" + modelo + "%" + marca + "%" + color + "%" + submarca + "%" + placas + "%" + kilometraje + "%" + numeroDeSerie + "%" + nombreCliente + "%" + direccion + "%" + telefono + "%" + correo + "%" + ultimaVisita + "%" + observacionesMecanico + "-" + "%" + observacionesCliente + "-" + "%" + "\n");
                            while (scan.hasNextLine()) {
                                filecontent = filecontent.concat(scan.nextLine() + "\n");
                            }
                            try {
                                FileWriter writer = new FileWriter("miArchivo2.txt");
                                writer.write(filecontent);
                                writer.close();;
                                reader.close();

                            } catch (IOException ex) {
                                Logger.getLogger(vistaRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(vistaRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        mostrarMensajeEmergente("Registro", "Registro exitoso");

                    }
                } finally {
                    try {
                        if (reader != null) {

                            reader.close();
                        }

                    } catch (IOException e) {
                    }
                }

            } catch (Exception e) {
                mostrarMensajeEmergente("Error", "El código debe de ser un número ");
            }

        } else {

            mostrarMensajeEmergente("Error", "No puedes tener espacios en Blanco");

        }

    }

    private void buscarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    }//GEN-LAST:event_registrarjButtonActionPerformed

    private void jButtonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtras1ActionPerformed
        new VistaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtras1ActionPerformed

    private void seleccionarSubmarca(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seleccionarSubmarca
        submarcaComboBox.removeAllItems();

        switch ((String) marcaComboBox.getSelectedItem()) {

            case "Ford":
                for (String sub : subMarcasFord) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Chevrolet":
                for (String sub : subMarcasChevrolet) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Nissan":
                for (String sub : subMarcasNissan) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Acura":
                for (String sub : subMarcasAcura) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Alfa Romeo":
                for (String sub : subMarcasAlfaRomeo) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Aston Martin":
                for (String sub : subMarcasAstonMartin) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Audi":
                for (String sub : subMarcasAudi) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "BAIC":
                for (String sub : subMarcasBAIC) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Bentley":
                for (String sub : subMarcasBentley) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "BMW":
                for (String sub : subMarcasBMW) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Cadillac":
                for (String sub : subMarcasCadillac) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Chrysler":
                for (String sub : subMarcasChrysler) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Dodge":
                for (String sub : subMarcasDODGE) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Ferrari":
                for (String sub : subMarcasFerrari) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Fiat":
                for (String sub : subMarcasFiat) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "GMC":
                for (String sub : subMarcasGMC) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Honda":
                for (String sub : subMarcasHonda) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Hyundai":
                for (String sub : subMarcasHyundai) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Infiniti":
                for (String sub : subMarcasInfiniti) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Jaguar":
                for (String sub : subMarcasJaguar) {
                    submarcaComboBox.addItem(sub);
                }
                break;

            case "Jeep":
                for (String sub : subMarcasJeep) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "KIA":
                for (String sub : subMarcasKIA) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Mazda":
                for (String sub : subMarcasMazda) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Mercedes Benz":
                for (String sub : subMarcasMercedesBenz) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Mitsubishi":
                for (String sub : subMarcasMitsubishi) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Peugeot":
                for (String sub : subMarcasPeugeot) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Renault":
                for (String sub : subMarcasRenault) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "SEAT":
                for (String sub : subMarcasSeat) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Subaru":
                for (String sub : subMarcasSubaru) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Suzuki":
                for (String sub : subMarcasSuzuki) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Tesla":
                for (String sub : subMarcasTesla) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Toyota":
                for (String sub : subMarcasToyota) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Volkswagen":
                for (String sub : subMarcasVolkswagen) {
                    submarcaComboBox.addItem(sub);
                }
                break;
            case "Volvo":
                for (String sub : subMarcasVolvo) {
                    submarcaComboBox.addItem(sub);
                }
        }
    }//GEN-LAST:event_seleccionarSubmarca

    public static void mostrarMensajeEmergente(String titulo, String mensaje) {

        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.OK_OPTION);

    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRegistrar().setVisible(true);
            }
        });
    }

    private void cargarElementosAComboBox() {

        for (String servicio : servicios) {
            nombreServiciojComboBox.addItem(servicio);
        }

        for (String mecanico : mecanicos) {
            mecanicoAsignadojComboBox.addItem(mecanico);
        }

        for (String color : colores) {
            colorComboBox.addItem(color);
        }

        for (String marca : marcas) {
            marcaComboBox.addItem(marca);
        }

        for (int i = 1995; i < 2020; i++) {
            modeloComboBox.addItem(Integer.toString(i));

        }
    }

    public String marcas[] = {"Selecciona...", "Ford", "Chevrolet", "Nissan", "Acura", "Alfa Romeo", "Aston Martin", "Audi",
        "BAIC", "Bentley", "BMW", "Cadillac", "Chrysler", "DODGE", "Ferrari", "Fiat", "GMC", "Honda", "Hyundai", "Infiniti",
        "Jaguar", "Jeep", "KIA", "Mazda", "Mercedes Benz", "Mitsubishi", "Peugeot", "Renault", "SEAT", "Subaru",
        "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo"};
    public String colores[] = {"Selecciona...", "Rojo", "Azul", "Blanco", "Negro", "Amarillo", "Verde", "Gris"};
    public String mecanicos[] = {"Selecciona...", "Jaime Prieto", "José Gutiérrez", "Arturo Gómez", "Luis Padilla", "Julián Gonzalez"};
    public String servicios[] = {"Servicio completo", "Servicio menor", "Cambio de aceite", "Filtro de aire", "Filtro de aceite"};
    public String subMarcasFord[] = {"B-MAX", "C-MAX", "EcoSport", "Edge", "Fiesta", "Focus", "Galaxy", "GT", "Ka+", "Kuga", "Mondeo", "Mustang",
        "Ranger", "S-Max", "Tourneo", "Transit"};
    public String subMarcasChevrolet[] = {"Aveo", "Camaro", "Captiva", "Corvette", "Cruze", "Malibu", "Orlando", "Spark", "Trax", "Volt"};
    public String subMarcasNissan[] = {"370Z", "Evalia", "GT-R", "Juke", "Leaf", "Micra", "Navara", "NV300", "Pulsar", "Qashqal", "X-Trail"};
    public String subMarcasAcura[] = {"Acura Rx", "Acura Xd", "Acura Xl"};
    public String subMarcasAlfaRomeo[] = {"4C", "Giulia", "Giulietta", "MiTo", "Stelvio"};
    public String subMarcasAstonMartin[] = {"DB11", "DB9", "DBX", "Rapide", "Vanquish", "Vantage"};
    public String subMarcasAudi[] = {"A1", "A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "Q1", "Q2", "Q3", "Q4", "Q5", "Q7", "Q8", "R8", "TT"};
    public String subMarcasBAIC[] = {"BJ40", "D20", "X35", "X60"};
    public String subMarcasBentley[] = {"Bentayga", "Continental GT", "Flying Spur", "Mulsanne"};
    public String subMarcasBMW[] = {"i3", "i8", "Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "Serie 6", "Serie 7", "Serie 8", "X1", "X2", "X3",
        "X4", "X5", "X6", "X7", "Z4"};
    public String subMarcasCadillac[] = {"ATS", "CT6", "CTS", "Escalade", "SRX", "XT5"};
    public String subMarcasChrysler[] = {"Chrysler 200", "Chrysler 300C", "Chrysler PT Cruiser", "Chrysler Crossfire"};
    public String subMarcasDODGE[] = {"Dodge Nitro", "Dodge Mirada", "Dodge Neon", "Dodge Dakota", "Dodge Dayton"};
    public String subMarcasFerrari[] = {"488 GTB", "812 Superfast", "California T", "F12 Berlinetta", "F8 Tributo", "GTC4 Lusso", "LaFerrari", "Portofino", "Purosangue"};
    public String subMarcasFiat[] = {"124 Spider", "500", "500L", "500X", "Doblo", "Fullback", "Panda", "Punto", "Tipo"};
    public String subMarcasGMC[] = {"GMC Terrain", "GMC Sierra"};
    public String subMarcasHonda[] = {"Civic", "CR-V", "HR-V", "Jazz", "NSX"};
    public String subMarcasHyundai[] = {"Elantra", "Genesis", "Grand Santa Fe", "i10", "i20", "i30", "i40", "Ioniq", "ix20", "Kona", "Nexo", "Palisade",
        "Santa Fe", "Tucson", "Veloster"};
    public String subMarcasInfiniti[] = {"Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX70"};
    public String subMarcasJaguar[] = {"E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "XJ"};
    public String subMarcasJeep[] = {"Cherokee", "Compass", "Grand Cherokee", "Renegade", "Wrangler"};
    public String subMarcasKIA[] = {"Carens", "Cee'd", "Niro", "Optima", "Picanto", "Rio", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Telluride", "Venga"};
    public String subMarcasMazda[] = {"2", "3", "6", "CX-3", "CX-30", "CX-4", "CX-5", "MX-5"};
    public String subMarcasMercedesBenz[] = {"AMG GT", "Citan", "CLA", "Clase A", "Clase B", "Clase C", "Clase E", "Clase G", "Clase S", "Clase V", "Clase X", "CLS",
        "EQC", "GLA", "GLB", "GLC", "GLE", "GLS", "SL", "SLC"};
    public String subMarcasMitsubishi[] = {"ASX", "Eclipse Cross", "i-MIEV", "L200", "Montero", "Outlander", "Space Star"};
    public String subMarcasPeugeot[] = {"108", "2008", "208", "3008", "308", "5008", "508", "Bípper", "iOn", "Partner", "Rifter", "Traveller"};
    public String subMarcasRenault[] = {"Arkana", "Captur", "Clio", "Espace", "Kadjar", "Kangoo", "Koleos", "Mégane", "Scenic", "Talismán", "Trafic", "Twingo"};
    public String subMarcasSeat[] = {"Alhambra", "Arona", "Ateca", "el-Born", "Ibiza", "León", "Mii", "Minimó", "Tarraco", "Toledo"};
    public String subMarcasSubaru[] = {"BRZ", "Forester", "Impreza", "Levorg", "Outback", "WRX STI", "XV"};
    public String subMarcasSuzuki[] = {"Baleno", "Celerio", "Ignis", "Jimny", "Swift", "SX4 / S-Cross", "Vitara"};
    public String subMarcasTesla[] = {"Model 3", "Model S", "Model X", "Model Y", "Roadster"};
    public String subMarcasToyota[] = {"Auris", "Avensis", "Aygo", "C-HR", "Corolla", "GT86", "Hilux", "Land Cruiser", "Prius", "ProAce", "RAV4", "Supra", "Verso", "Yaris"};
    public String subMarcasVolkswagen[] = {"Amarok", "Arteon", "Beetle", "Caddy", "California", "Caravelle", "Crafter", "Golf", "Multivan", "Passat", "Polo", "Scirocco",
        "Sharan", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "UPI"};
    public String subMarcasVolvo[] = {"S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90"};
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JTextField correoClienteTextField;
    private javax.swing.JTextField costojTextField;
    private javax.swing.JTextField direccionClienteTextField;
    private javax.swing.JTextField fechaEntregajTextField;
    private javax.swing.JTextField fechaLLegadajTextField;
    private javax.swing.JTextField idDeServiciojTextField;
    private javax.swing.JButton jButtonAtras1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kilometrajeTextField;
    private javax.swing.JComboBox<String> marcaComboBox;
    private javax.swing.JComboBox<String> mecanicoAsignadojComboBox;
    private javax.swing.JComboBox<String> modeloComboBox;
    private javax.swing.JTextField nombreClienteTextField;
    private javax.swing.JComboBox<String> nombreServiciojComboBox;
    private javax.swing.JTextField numeroSerieTextField;
    private javax.swing.JTextField numeroTelefonicoTextField;
    private javax.swing.JTextField observacionesClientejTextField;
    private javax.swing.JTextField observacionesMecanicojText;
    private javax.swing.JTextField placasTextField;
    private javax.swing.JButton registrarjButton;
    private javax.swing.JComboBox<String> submarcaComboBox;
    private javax.swing.JTextField ultimaVisitaTextField;
    // End of variables declaration//GEN-END:variables
}
